import type { Dict } from "../i18n";

export const en: Dict = {
  "punct.comma": ",",
  "punct.stop": ".",
  "state.on": "on",
  "state.off": "off",
  "nav.chapters": "Chapters",
  "nav.about": "About",
  "nav.dark": "Dark",
  "nav.light": "Light",
  "nav.toLight": "Switch to light theme",
  "nav.toDark": "Switch to dark theme",
  "nav.contents": "Contents",
  "nav.menu": "Open menu",
  "nav.close": "Close menu",
  "nav.theme": "Theme",
  "nav.language": "Language",

  "site.tagline": "A free interactive primer",
  "site.deck":
    "Since 2018, \u201cworld model\u201d has meant at least five different machines, and the people saying it rarely tell you which. This primer pulls the five apart, then shows how each one works and where it came from.",
  "site.begin": "Begin Chapter 01",
  "site.meta": "{n} chapters · {time} · no signup",
  "site.book": "Whole book (PDF)",
  "home.h1": "World Models",
  "home.runtimeHm": "{h}h {m}m",
  "home.runtimeM": "{m}m",
  "home.chapterCount": "{n} chapters",
  "home.premise.p1":
    "Ask four labs what a world model is and you get four different machines that do not fit together. Each has its own history. Genie, from Google DeepMind, generates video you steer with the arrow keys. Marble, from World Labs, builds 3D geometry a robot can be trained inside. Dreamer, from Danijar Hafner's group, learns a small simulator and plans against it. V-JEPA, from Meta, predicts embeddings and throws the prediction away.",
  "home.premise.p2":
    "A fifth camp is not describing a machine at all. When people argue about whether a language model \u201chas a world model\u201d, they mean structure found inside a network that was trained for something else. The evidence comes from interpretability work, not from anything you could run. That is why two people can agree on every fact and still argue. One is asking whether a system can simulate. The other is asking whether a network contains something.",
  "home.premise.p3":
    "Under the naming mess is a real and old subject with a clear line of descent. It starts in 1960 with the Kalman filter, the maths that lets a radar track a plane from noisy blips. It passes through 1990, when J\u00fcrgen Schmidhuber and Richard Sutton first put a learned model of the world next to something that used it to act. It arrives at the four machines above.",
  "home.who1.t": "The engineer",
  "home.who1.b":
    "You ship models but the RL-adjacent literature has always felt like a different country. You want a map of it.",
  "home.who2.t": "The researcher next door",
  "home.who2.b":
    "You work in another subfield and need to know what people mean when they say a video model understands physics.",
  "home.who3.t": "The student",
  "home.who3.b":
    "You have the maths and the time and want a path through the papers that is ordered rather than alphabetical.",
  "home.who4.t": "The sceptic",
  "home.who4.b":
    "You suspect a lot of this is overclaimed. Chapter 9 is for you, and you are probably partly right.",
  "home.metaDescription":
    "A free interactive primer on world models. The phrase covers at least five different machines; this pulls them apart, then shows how each one works.",
  "home.contents": "Contents",
  "home.mapTitle": "Five things people mean",
  "home.mapNote": "If you are not sure which kind you have been reading about, start here.",
  "home.premise": "The premise",
  "home.audience": "Who this is for",
  "chapter.read": "{n} min read · interactive",
  "chapter.pdf": "PDF",
  "chapter.printNote": "The figures in this chapter are interactive. Press and drag them online at {url}.",
  "chapter.prev": "← Previous",
  "chapter.next": "Next →",
  "chapter.start": "Start",
  "chapter.atBeginning": "You’re at the beginning",
  "chapter.untranslated":
    "This chapter is not in {lang} yet, so the text below is the English original.",
  "chapter.soon": "Soon",
  "chapter.drafting": "Drafting",
  "chapter.min": "{n} min",
  "chapter.readArrow": "Read →",

  "map.ordered": "Ordered by what they predict",
  "map.predicts": "Predicts {x}",
  "rb.aria": "Two models rolled out from an initial offset of {n} per cent: one diverges and one returns to the demonstrated path.",
  "rb.truthOnly": "trained only on the demonstrated path",
  "rb.recovery": "trained to recover from nearby states",
  "rb.demonstrated": "demonstrated path",
  "rb.first": "first prediction",
  "rb.later": "ten steps later",
  "rb.offset": "Starting offset",
  "rb.oneStep": "On the demonstrated path",
  "rb.oneStepA": "both predict perfectly",
  "rb.truthEnd": "Truth-only error at step 10",
  "rb.recoveryEnd": "Recovery-trained error at step 10",
  "id.nominal": "Transitions counted by the training log",
  "id.real": "Real transitions",
  "id.dreamUseful": "Useful imagined transitions",
  "id.effective": "Effective experience",
  "id.v.good": "The model is accurate enough here that most of the synthetic batch still carries signal.",
  "id.v.thin": "The log says 100 transitions. After discounting compounding model error, the learner receives rather less.",
  "id.v.bad": "The synthetic batch is large enough, and unreliable enough, to pad the counter while starving the learner.",
  "id.share": "Imagined share",
  "id.error": "Model error per step",
  "id.reliability": "Synthetic reliability",
  "id.contactCost": "World-contact cost",
  "id.computeCost": "Model compute cost",
  "fs.mean": "Predict the mean",
  "fs.samples": "Sample futures",
  "fs.left": "left future",
  "fs.average": "squared-error optimum",
  "fs.right": "right future",
  "fs.leftChance": "Chance of left",
  "fs.draw": "Draw again",
  "fs.sharp": "Individual prediction",
  "fs.sharp.no": "Blurred: it lands between outcomes.",
  "fs.sharp.yes": "Sharp: each draw is a possible outcome.",
  "fs.uncertainty": "Uncertainty",
  "fs.uncertainty.kept": "Kept as a distribution of futures.",
  "fs.uncertainty.lost": "Collapsed into one average image.",
  "af.aria": "Three commanded trajectories under a model with {n} per cent action fidelity.",
  "af.command.0": "command left",
  "af.command.1": "command straight",
  "af.command.2": "command right",
  "af.sameStart": "same starting frame",
  "af.realized": "realised motion",
  "af.fidelity": "Action fidelity",
  "af.input": "Action input",
  "af.input.yes": "present in every row",
  "af.separation": "Left-right separation",
  "af.verdict": "Control test",
  "af.v.ignored": "The model mostly ignores the command.",
  "af.v.weak": "The command changes the video, but weakly.",
  "af.v.strong": "Different commands produce distinct trajectories.",
  "fm.risk.persistence": "Persistence",
  "fm.risk.action": "Action fidelity",
  "fm.risk.horizon": "Long horizon",
  "fm.risk.target": "Target quality",
  "fm.risk.verification": "Verification",
  "fm.contract.renderer": "Renderer",
  "fm.contract.simulator": "Simulator",
  "fm.contract.dynamics": "Dynamics model",
  "fm.contract.representation": "Representation",
  "fm.contract.implicit": "Implicit model",
  "fm.level.0": "not central",
  "fm.level.1": "low risk",
  "fm.level.2": "material risk",
  "fm.level.3": "binding risk",
  "fm.askFirst": "For a {system}, ask this first",
  "fm.question.persistence": "Does the same object remain itself after it leaves view and returns?",
  "fm.question.action": "Do different commands reliably cause the corresponding different futures?",
  "fm.question.horizon": "How far can it run on its own outputs before the answer stops supporting a decision?",
  "fm.question.target": "What information is the training target allowed to discard or collapse?",
  "fm.question.verification": "What observation could prove the claimed internal model is not there?",
  "fm.contract": "System contract",
  "fm.binding": "Binding question",
  "wb.steps": "Steps into the rollout",
  "wb.holdsTo": "holds to about {n}",
  "wb.colour": "colours and lighting stay put",
  "wb.texture": "surfaces keep looking like themselves",
  "wb.layout": "the room stays the same shape",
  "wb.count": "there are still the same number of things",
  "wb.physics": "things fall and collide the way they should",
  "wb.identity": "that is still the same object it was",
  "wb.gone": "gone",
  "wb.holding": "holding",
  "wb.brokenCount": "Properties already lost",
  "wb.stillLooks": "And yet",
  "wb.v.fine": "Nothing has gone yet. Everything downstream can still be trusted.",
  "wb.v.looksOk": "It still looks convincing. The things that broke are not the things you look at.",
  "wb.v.gone": "It still looks like a scene. It is no longer a scene about anything in particular.",
  "nr.fidelity": "Looks right",
  "nr.consistency": "Stays consistent",
  "nr.control": "Does what you tell it",
  "nr.cost": "Cheap to run",
  "nr.sys.a": "System A",
  "nr.sys.b": "System B",
  "nr.sys.c": "System C",
  "nr.fidelity.note": "Frame quality, which is what demos are made of and what a per-pixel score rewards.",
  "nr.consistency.note": "Whether the world holds together over a long rollout, which is what an agent needs and what demos are too short to show.",
  "nr.control.note": "Whether the action you gave it is the action it took, which is the difference between a world model and a video.",
  "nr.cost.note": "What it takes to run one rollout, which decides whether anything can afford to search inside it.",
  "nr.bestBy": "Best by this measure",
  "nr.overall": "Best overall",
  "nr.overallA": "There is no agreed way to combine these, so the question does not currently have an answer.",
  "ep.speed": "Launch speed",
  "ep.band": "the speeds it was trained on",
  "ep.axis": "how hard it was thrown",
  "ep.faster": "harder",
  "ep.true": "Where it really lands",
  "ep.says": "Where the model says",
  "ep.off": "Off by",
  "ep.inside": "Inside the band it was shown. Anyone testing here would say it has the rule.",
  "ep.outside": "Outside the band. It does not have the rule; it has a line through the part it saw.",
  "ep.aria": "True projectile range and a model's prediction across launch speeds, at {v} metres per second where the model is off by {e} per cent.",
  "ac.left": "hold left",
  "ac.straight": "hold nothing",
  "ac.right": "hold right",
  "ac.none": "no action",
  "ac.given": "the first two frames are given",
  "ac.made": "the rest are made up",
  "ac.action": "Action",
  "ac.condOn": "Action fed in",
  "ac.condOff": "No action fed in",
  "ac.note.on": "One model, one start, three futures. Which one you get is up to you.",
  "ac.note.off": "All three rows are identical. Without an action there is one future on offer: whichever the model finds most likely.",
  "pb.chance": "Chance it goes up",
  "pb.up": "one possible future ({p}%)",
  "pb.down": "the other one ({p}%)",
  "pb.best": "the best possible pixel prediction",
  "pb.q": "Is the middle panel a thing that can happen?",
  "pb.a.blur": "No. It is both futures at once, and neither of them is that.",
  "pb.a.sure": "Nearly. With one outcome almost certain, the average is almost that outcome.",
  "pb.scoreQ": "Does it score better than either real future?",
  "pb.scoreA": "Yes. Squared error over a set of outcomes is minimised by their average, so the optimum is a picture of nothing.",
  "cl.loss": "how close the prediction is",
  "cl.spread": "how much the representation still says",
  "cl.axis": "training steps",
  "cl.step": "Step",
  "cl.guardOff": "No safeguard",
  "cl.guardOn": "Safeguard on",
  "cl.verdict": "What you have got",
  "cl.v.dead": "A perfect score and an empty representation. Everything encodes to the same point.",
  "cl.v.going": "On its way down. The cheapest way to be right is to stop saying anything.",
  "cl.v.alive": "A worse loss that never reaches zero, and a representation that still distinguishes things.",
  "cl.aria": "Loss and representation spread over training, with the anti-collapse safeguard {g}.",
  "db.real": "steps taken in the world",
  "db.imagined": "steps taken inside the model",
  "db.ratio": "Imagined steps per real one",
  "db.contact": "Time spent in the world",
  "db.wall": "Total time, imagining included",
  "db.versus": "If it were all real",
  "db.note": "The learner needs {total} steps of experience from somewhere. Sliding the ratio does not change that. It changes where the steps come from, and which budget pays.",
  "db.v.none": "No model. Every step of experience is bought from the world at full price.",
  "db.v.some": "Most of the experience is now imagined, and the contact time falls with it.",
  "db.v.lots": "Almost all of it is imagined. Whether the model can supply that is a later figure's problem.",
  "dt.temp": "Uncertainty in the dream",
  "dt.inDream": "score inside the dream",
  "dt.inWorld": "score in the world",
  "dt.gap": "Dream minus world",
  "dt.axisLow": "a confident dream",
  "dt.axisHigh": "a dream too noisy to learn in",
  "dt.v.exploit": "Brilliant in there, useless out here. The policy found the model's quirks and built on them.",
  "dt.v.good": "Hard enough in there that only things which really work survive.",
  "dt.v.noise": "Now there is no task left to learn. Both scores collapse.",
  "dt.aria": "Score inside the dream and score in the world, drawn against how much uncertainty the dream is given, at a setting of {t}.",
  "fr.steps": "Steps rolled forward",
  "fr.bias": "How wrong the model is, per step",
  "fr.real": "what actually happens",
  "fr.forced": "corrected every step, as in training",
  "fr.free": "left to run on its own answers",
  "fr.offForced": "Off by, corrected",
  "fr.offFree": "Off by, on its own",
  "fr.ratio": "Worse by",
  "fr.aria": "The same flawed model rolled forward {n} steps with a {b} per cent per-step bias, drawn once corrected at every step and once left to consume its own output.",
  "mt.recurrent": "Carry a summary",
  "mt.attention": "Keep a context window",
  "mt.length": "Steps so far",
  "mt.carried": "Numbers carried forward",
  "mt.carried.note": "What the model is holding when the next step arrives.",
  "mt.perStep": "Work for one more step",
  "mt.perStep.note": "Multiply-adds to fold in one new observation.",
  "mt.reach": "Can it still see the first step?",
  "mt.reach.rec": "Only if the summary kept it",
  "mt.reach.att": "Yes, while it remains in context",
  "mt.reach.note": "Whatever a fixed summary dropped is not recoverable later.",
  "mt.width": "Both columns use a state {d} numbers wide, so the only thing changing is the length.",
  "mt.short": "Short enough that looking at everything is the cheaper option.",
  "mt.mid": "Past the crossover. Keeping everything now costs more per step than updating a summary.",
  "mt.long": "This is where the fixed summary earns its keep, and where it starts losing things.",
  "lr.decoded": "the room those two numbers decode to",
  "lr.pad": "the space itself. drag anywhere in it",
  "lr.z1": "How far the wall is",
  "lr.z2": "Where the way through is",
  "lr.picture": "Numbers in the picture",
  "lr.description": "Numbers in the description",
  "lr.aria": "A room drawn from two numbers, a depth of {d} and an offset of {o}, beside the two-dimensional space those numbers are picked from.",
  "li.a": "one room",
  "li.b": "another room",
  "li.pixel": "average the two pictures",
  "li.latent": "average the two numbers, then decode",
  "li.blend": "How far between them",
  "li.pixelQ": "Is the blended picture a room?",
  "li.pixelNo": "No. It is two rooms at once, which is not a thing you could walk into.",
  "li.pixelYes": "At the ends, yes. Anywhere in between, no.",
  "li.latentQ": "Is the decoded one a room?",
  "li.latentYes": "Yes, everywhere along the slider. Every point in that space decodes to one.",
  "bn.width": "Numbers allowed through",
  "bn.depth": "how far the wall is",
  "bn.gap": "where the way through is",
  "bn.tilt": "which way the camera is tipped",
  "bn.clutter": "gravel on the floor",
  "bn.grain": "sensor noise",
  "bn.light": "how bright it is",
  "bn.canYouAct": "Could you decide what to do?",
  "bn.act.0": "No. Nothing came through at all.",
  "bn.act.1": "Not quite. You know how far, but not where the gap is.",
  "bn.act.2": "Yes. Two numbers is the whole decision.",
  "bn.spent": "What the extra width bought",
  "bn.spent.lean": "Nothing wasted yet. Everything through the squeeze changes what you would do.",
  "bn.spent.leaves": "Gravel, noise and lighting. Real detail, and none of it changes what you would do.",
  "bn.aria": "A room rebuilt from the first {k} of six numbers that describe it.",
  "fts.seen": "Frames seen",
  "fts.frame": "frame {n}",
  "fts.axis": "one ball, photographed a few times",
  "fts.known": "What you can work out",
  "fts.open": "What is still open",
  "fts.known.1": "Where it is. That is all a single picture can tell you.",
  "fts.known.2": "Where it is, which way it is going, and how fast.",
  "fts.known.3": "All of that, plus whether it is speeding up or slowing down.",
  "fts.open.1": "Every direction, and every speed. The picture rules out nothing.",
  "fts.open.2": "Whether the path bends, and which way.",
  "fts.open.3": "Little enough to commit to a guess.",
  "fts.aria": "A ball photographed several times, with the futures still consistent with {n} frames drawn as a fan that narrows as frames are added.",
  "pc.strength": "Predictor",
  "pc.bits": "bits",
  "pc.perChar": "Bits per character",
  "pc.message": "This message costs",
  "pc.saved": "Shorter by",
  "pc.none": "No model",
  "pc.letter": "Letter frequencies",
  "pc.bigram": "One letter of context",
  "pc.trigram": "Two letters of context",
  "pc.word": "Words and grammar",
  "pc.strong": "A good predictor",
  "pc.none.note": "Every symbol equally likely, so every symbol costs the same.",
  "pc.letter.note": "Knowing that e is common and q is not already buys you something.",
  "pc.bigram.note": "After q, u is nearly free. Context is where the savings live.",
  "pc.trigram.note": "Two letters of context, and most of what follows is already narrowed.",
  "pc.word.note": "Once it knows words and how they go together, whole endings are predictable.",
  "pc.strong.note": "Roughly where Claude Shannon put a person guessing English, and where good language models sit.",
  "gca.run": "Run",
  "gca.pause": "Pause",
  "gca.again": "Again",
  "gca.reset": "Reset",
  "gca.step": "Steps taken",
  "gca.real": "what arrived",
  "gca.guess": "what it guessed",
  "gca.wrongBy": "Recently wrong by",
  "gca.weights": "What it has learned",
  "gca.verdict": "How it is doing",
  "gca.v.bad": "Guessing. It has seen almost nothing yet.",
  "gca.v.mid": "Getting the shape, still late on the turns.",
  "gca.v.good": "Nearly on top of it. Nobody told it the rule.",
  "gca.aria": "A predictor guessing the next value of a sequence and correcting itself, shown after {n} steps.",
  "gallery.renderer": "A frame, then the next frame. What comes out is something to look at, and the room persists only because it kept drawing it consistently.",
  "gallery.simulator": "Geometry another program can open. Surfaces to render, and collider meshes underneath for a physics engine to bump into.",
  "gallery.dynamics": "A short vector, and the next one under an action you are considering. Nobody names the numbers. It only has to be rollable forward.",
  "gallery.representation": "The summary of the missing piece, predicted as a point in embedding space and then thrown away. It never redraws the pixels.",
  "gallery.implicit": "Not an output at all. A probe finds board state inside a network nobody handed a board to, which is a claim about what arose, not a thing you can run.",
  "map.offAxis": "Off the axis",
  "map.notASystem": "Not a system you run",
  "map.moreConcrete": "More concrete",
  "map.whatGetsPredicted": "what gets predicted",
  "map.moreAbstract": "more abstract",
  "map.howToTell": "How to tell",
  "map.prev": "Previous",
  "map.next": "Next",
  "map.counter": "{n} of {total}",
  "map.whoTalks": "Who talks this way",
  "map.coveredIn": "Covered in",
  "map.chapterN": "Chapter {n}",
  "map.idle":
    "Five things the phrase is used to mean. Four of them are systems you can run; the fifth is a claim about what is inside one. Pick any of them.",

  "spill.query": "“world model”",
  "spill.count": "5 incompatible answers",
  "spill.turnsOut": "Turns out to be",


  "loop.idle": "Every definition is a specialist on one arc of this loop. Hover any of them.",
  "loop.intervene": "intervene · the world is now different",
  "loop.observe": "observe",
  "loop.infer": "infer",
  "loop.predict": "predict",
  "loop.choose": "choose",

  "eq.hoverHint": "Hover any part of the equation, or any phrase beneath it.",
  "eq.next": "what happens next",
  "eq.now": "where you are now",
  "eq.act": "what you do",
  "eq.next.note": "The state one step into the future. This is the only part you do not know, and the only part the model produces.",
  "eq.now.note": "The current state. Given, not predicted.",
  "eq.act.note": "The action you take. Change this and the prediction changes, which is what makes the model useful for choosing.",
  "roll.one": "the next state",
  "roll.many": "every state from here to H",
  "roll.nowP": "the same single state you are in",
  "roll.plan": "a whole plan",
  "roll.one.note": "One step. This is the model from the figure above, unchanged.",
  "roll.many.note": "Not one prediction but a whole stretch of them, each one built on the last. The model has to eat its own output to get here, which is where the error compounds.",
  "roll.now.note": "This does not grow. However far ahead you ask, you are still standing in exactly one place with exactly one observation of it.",
  "roll.plan.note": "No longer one action but a sequence of them, which is what makes this a plan rather than a guess. Searching over these sequences is what planning is.",
  "roll.askFor": "Ask for ",
  "roll.insteadOf": " instead of ",
  "roll.stillGet": " and you still only get ",
  "roll.and": " and ",
  "loop.world": "World",
  "loop.observation": "Observation",
  "loop.belief": "Belief",
  "loop.imagination": "Imagination",
  "loop.action": "Action",
  "loop.world.sub": "hidden state sₜ",
  "loop.belief.sub": "internal state bₜ",
  "loop.imagination.sub": "possible futures",
  "arch.observation": "Observation",
  "arch.encoder": "Encoder",
  "arch.latent": "Latent",
  "arch.dynamics": "Dynamics",
  "arch.decoder": "Decoder",
  "arch.prediction": "Prediction",
  "arch.controller": "Controller",
  "arch.action": "action",
  "arch.stateEstimate": "State estimate",
  "arch.dynamicsGiven": "Dynamics (given)",
  "arch.dynamicsLearned": "Dynamics (learned)",
  "arch.latentDynamics": "Latent dynamics",
  "arch.imaginedRollout": "Imagined rollout",
  "arch.predEmbedding": "Predicted embedding",
  "arch.aWorld": "A world you can enter",

  "eq.reading": "the chance of",
  "eq.given": ", given ",
  "eq.and": " and ",
  "roll.hint": "Only two things changed. Hover either side to see which.",

  "quiz.verdict.ch3.all": "Including the last two. Prediction builds structure because structure is the cheap way to be less wrong, and low error on a recording is still only a claim about that recording.",
  "quiz.verdict.ch3.most": "Enough to read a paper with. The ones people miss are the probe and the target choice, which are both about what prediction is actually rewarding.",
  "quiz.verdict.ch3.few": "Worth another pass. Two questions settle most cases: what does the next thing depend on, and what is being put on the right-hand side of the guess.",
  "quiz.verdict.ch4.all": "Including the last two. Reconstruction is a proxy for keeping what matters, and the bottleneck decides what is available to everything after it.",
  "quiz.verdict.ch4.most": "Enough to read a paper with. The ones people miss are the proxy problem and why small is not the goal.",
  "quiz.verdict.ch4.few": "Worth another pass. Two questions settle most cases: what did the squeeze keep, and does the point between two valid points mean anything.",
  "quiz.verdict.ch5.all": "Including the first three. A one-step number measures a job the model will never be asked to do, and everything after that follows from it.",
  "quiz.verdict.ch5.most": "Enough to read a paper with. The ones people miss are the crossover and the two-part state, which are both about what a model is forced to give up.",
  "quiz.verdict.ch5.few": "Worth another pass. One question settles most cases: at this step, was it handed the truth, or its own last answer?",
  "quiz.verdict.ch6.all": "Including the last three. Imagination changes the exchange rate, and every safeguard in the chapter makes the grading harder to game rather than making it correct.",
  "quiz.verdict.ch6.most": "Enough to read a paper with. The ones people miss are the second lap, and why a trained policy is harder to catch than a plan.",
  "quiz.verdict.ch6.few": "Worth another pass. One question settles most cases: during training, who was marking the work?",
  "quiz.verdict.ch7.all": "Including the last two. An embedding loss stopped being a number you can read, and the argument is narrower than the slogan it usually arrives as.",
  "quiz.verdict.ch7.most": "Enough to read a paper with. The ones people miss are the fixed target you give up, and that this is not a case against generation as such.",
  "quiz.verdict.ch7.few": "Worth another pass. One question settles most cases: when the future is genuinely open, what is this loss asking the model to draw?",
  "quiz.verdict.ch8.all": "Including the middle three. Matching inside the band you trained on is exactly what a fitted function does, and the outputs being persuasive is not evidence.",
  "quiz.verdict.ch8.most": "Enough to read a paper with. The ones people miss are what consistency actually rests on, and why these are the wrong shape to plan inside.",
  "quiz.verdict.ch8.few": "Worth another pass. One question settles most cases: was this demonstration inside the range it was trained on?",
  "quiz.verdict.ch9.all": "Including the last one. What does it output, and can you roll it forward under actions nobody took. That question survives the whole course.",
  "quiz.verdict.ch9.most": "Enough to read a paper with. The ones people miss are why the average error stays low, and why task success does not settle it.",
  "quiz.verdict.ch9.few": "Worth another pass. One question settles most cases: which measure is this claim using, and what does that measure ignore?",
  "quiz.verdict.ch1.all": "Including the trap. What a system is aimed at does not decide the category; what it outputs does.",
  "quiz.verdict.ch1.most": "Enough to read a paper with. The ones people miss are the trap, and the fact that staying consistent proves nothing on its own.",
  "quiz.verdict.ch1.few": "Worth another pass. Two questions settle most cases: what does it actually output, and what are you given to start from.",
  "quiz.verdict.ch2.all": "Including the two about trust. A model earns its keep by predicting consequences, and loses it the moment a search is allowed to outrun the evidence.",
  "quiz.verdict.ch2.most": "Enough to read a paper with. The ones people miss are the ensemble and the counterfactual, which are both questions about how far a model's authority reaches.",
  "quiz.verdict.ch2.few": "Worth another pass. Two questions settle most cases: can you run it forward under actions nobody took, and where is it allowed to be wrong.",
  "dyn.hint": "Hover any part of the formula, or any phrase beneath it.",
  "dyn.hat": "learned, so only an estimate",
  "dyn.next": "where you end up",
  "dyn.worth": "what the step was worth",
  "dyn.now": "where you are now",
  "dyn.act": "an action you might take",
  "dyn.hat.note": "The hat is the whole chapter in one mark. It says estimated. This is a model fitted from experience, not the world, and everything that goes wrong later goes wrong because of it.",
  "dyn.next.note": "The state one step on. Produced by the model, not observed. This is the only part nobody handed you.",
  "dyn.worth.note": "The reward. Not every learned model predicts one, but a planner needs something to score against, so most do.",
  "dyn.now.note": "Where you are, compressed. It need not be a position and a speed. It need only carry whatever the next prediction depends on.",
  "dyn.act.note": "The action. Change this and the prediction changes, which is the whole reason the thing is any use for choosing.",
  "dyn.read.0": "given ",
  "dyn.read.1": " and ",
  "dyn.read.2": ", what to expect for ",
  "dyn.read.3": " and ",
  "dyn.read.4": ".",
  "am.modelScore": "what the model scores",
  "am.realScore": "what really happens",
  "am.notEqual": "is not the same as",
  "am.unless": "unless the model is good where the search goes looking.",
  "am.bestModel": "best, says the model",
  "am.bestReal": "best, in fact",
  "am.axis": "every action you could take",
  "am.pick": "Pick an action",
  "am.agree": "Here the two agree, and most of the space looks like this.",
  "am.diverged": "Here they do not. This is the stretch the model had least to learn from.",
  "am.modelSays": "Model says",
  "am.reallyGet": "Really get",
  "am.aria": "Two scoring curves over the same set of actions. They agree almost everywhere, and come apart at one narrow spike the model believes in.",
  "comp.horizon": "Steps ahead",
  "comp.given": "given by the world",
  "comp.imagined": "the model reading its own answers",
  "comp.errorAxis": "how wrong it is by now",
  "comp.perStep": "The model's own error, per step",
  "comp.gain": "Amplification per step",
  "comp.gainStat": "Amplification per step",
  "comp.linear": "At 1.00 nothing is amplified, so the error just adds up. Straight line, no surprises.",
  "comp.after": "Error after {h} steps",
  "comp.fine": "Still close enough to act on.",
  "comp.drifting": "Drifting. Nothing broke, it just kept adding up.",
  "comp.gone": "Nowhere near. Same model, same error per step.",
  "comp.aria": "A chain of predicted states, the first given and the rest produced by the model from its own output. With the model adding two per cent of its own error each step and existing error amplified {gain} times per step, the accumulated error after {h} steps reaches {pct} per cent.",
  "serve.watch.short": "watch",
  "serve.decide.short": "decide",
  "serve.swing.short": "move + swing",
  "serve.readToss.short": "read the toss",
  "serve.swingEarly.short": "move + swing, 177 ms",
  "serve.net": "net",
  "serve.server": "server",
  "serve.returner": "returner",
  "serve.speed": "Serve speed",
  "serve.contact": "racket hits ball",
  "serve.ball": "the ball",
  "serve.arrives": "ball arrives",
  "serve.react": "Wait and see",
  "serve.early": "Read it early",
  "serve.watch": "watches",
  "serve.decide": "works out where it goes",
  "serve.swing": "moves and swings",
  "serve.swingEarly": "moves and swings, from 177 ms",
  "serve.short": "short",
  "serve.readToss": "reads the toss",
  "serve.inTime": "in time",
  "serve.late": "{n} ms too late",
  "serve.play": "Serve",
  "serve.flight": "Time from racket to returner",
  "serve.verdictLabel": "At this speed",
  "serve.bothWork": "Slow enough that watching the ball still works. Both get there.",
  "serve.onlyEarly": "Too fast to watch. Only the player who had already decided arrives in time.",
  "serve.neither": "Past the point where even an early read is comfortable. Returns here are a block, not a shot.",
  "serve.aria": "A time budget for returning a {kmh} kilometre per hour serve that takes {ms} milliseconds to arrive, comparing a returner who watches the ball against one who committed off the toss.",
  "exp.effort": "Search effort",
  "exp.phantom": "gap the model believes in",
  "exp.realGap": "the only real gap",
  "exp.inModel": "In the model",
  "exp.inReality": "In reality",
  "exp.succeeded": "Reached the goal",
  "exp.failed": "Hit the wall",
  "exp.honest": "Not enough search to find the flaw. It takes the long way round, and it works.",
  "exp.stuck": "Still searching.",
  "exp.exploited": "It found the gap that is not there. Perfect in imagination, wall in reality.",
  "exp.aria": "A plan routed through a gap the model believes in, drawn against the same plan executed in a world where that gap is solid.",
  "plan.tried": "Sequences tried",
  "plan.considered": "Considered",
  "plan.hitWall": "Would have hit the wall",
  "plan.bestMiss": "Best distance from goal",
  "plan.found": "Found a way round.",
  "plan.allHit": "Every sequence so far runs into the wall.",
  "plan.closest": "Closest so far, still short.",
  "plan.aria": "A planner sampling {n} action sequences, rolling each through its model and keeping the best.",
  "hz.horizon": "Horizon H",
  "hz.gapEvery": "gap, every step",
  "hz.steps": "Steps predicted",
  "hz.gapNow": "Gap right now",
  "hz.worst": "Worst gap so far",
  "hz.units": "{n} step-widths",
  "hz.v0": "Indistinguishable so far.",
  "hz.v1": "Drifting apart.",
  "hz.v2": "Visibly different futures.",
  "hz.v3": "One bounced a step late, and they never recovered.",

  "quiz.of": "{i} / {n}",
  "quiz.score": "Score {n}",
  "quiz.which": "Which definition is it?",
  "quiz.pick": "Pick one",
  "quiz.right": "Right",
  "quiz.wrong": "Not quite",
  "quiz.correct": "✓ correct",
  "quiz.yours": "✗ your answer",
  "quiz.yoursShort": "✗ yours",
  "quiz.next": "Next",
  "quiz.seeScore": "See score",
  "quiz.scored": "You scored",
  "quiz.again": "Again",
  "quiz.answer": "Answer",

  "video.nothing": "Nothing to watch",
  "video.talk": "Talk",

  "foot.body":
    "A free primer on world models. Free to read, free to share, free to steal for your own course. Attribution appreciated.",
  "byline.by": "By",
  "star.title": "Everything here is open source",
  "star.body": "The prose, the figures and every interactive on this site are in one public repository. Read it, correct it, lift a component for your own writing. If it was useful, a star is the cheapest way to help somebody else find it.",
  "star.compact": "This chapter is free and open source. A star helps the next person find it.",
  "star.button": "Star on GitHub",
  "foot.about": "About",
  "foot.source": "Source",
};
