import type { Dict } from "../i18n";

export const zh: Dict = {
  "punct.comma": "，",
  "punct.stop": "。",
  "state.on": "开",
  "state.off": "关",
  "nav.chapters": "章节",
  "nav.about": "关于",
  "nav.dark": "深色",
  "nav.light": "浅色",
  "nav.toLight": "切换到浅色主题",
  "nav.toDark": "切换到深色主题",
  "nav.contents": "目录",
  "nav.menu": "打开菜单",
  "nav.close": "关闭菜单",
  "nav.theme": "主题",
  "nav.language": "语言",

  "site.tagline": "免费的交互式入门读物",
  "site.deck":
    "自 2018 年起，「世界模型」这个词至少指过五种不同的机器，而说的人很少告诉你是哪一种。这份读物先把这五种分开，再讲每一种怎么工作、从哪里来。",
  "site.begin": "从第 01 章开始",
  "site.book": "全书 PDF",
  "home.h1": "World Models",
  "home.chapterCount": "共 {n} 章",
  "home.premise.p1":
    "问四家实验室什么是世界模型，你会得到四台互不相容的机器，每一台都有自己的来历。Google DeepMind 的 Genie 生成你可以用方向键操控的视频。World Labs 的 Marble 造出机器人可以在里面训练的三维几何。Danijar Hafner 团队的 Dreamer 学出一个小型仿真器，并在上面做规划。Meta 的 V-JEPA 预测嵌入向量，然后把预测扔掉。",
  "home.premise.p2":
    "第五拨人根本不是在描述一台机器。当人们争论一个语言模型「有没有世界模型」时，他们说的是在一个为别的任务训练出来的网络内部发现的结构。支持这个说法的证据来自可解释性研究，而不是任何你能运行的东西。所以两个人可以在每一个事实上都一致，却依然吵得起来：一个问的是系统能不能模拟，另一个问的是网络里面有没有某种东西。",
  "home.premise.p3":
    "命名的混乱底下，是一个真实而古老的题目，而且有一条清楚的传承线。它从 1960 年的卡尔曼滤波器开始，那是让雷达从带噪的回波里跟住一架飞机的数学。它经过 1990 年，那一年 Jürgen Schmidhuber 和 Richard Sutton 第一次把一个学出来的世界模型，摆在一个会拿它去行动的东西旁边。它一路走到上面那四台机器。",
  "home.who1.t": "工程师",
  "home.who1.b": "你在做模型，但强化学习那一带的文献一直像另一个国家。你想要一张它的地图。",
  "home.who2.t": "隔壁方向的研究者",
  "home.who2.b": "你做的是另一个子领域，需要知道别人说一个视频模型「懂物理」时，到底指的是什么。",
  "home.who3.t": "学生",
  "home.who3.b": "你有数学基础也有时间，想要一条按顺序走的论文路线，而不是一份按字母排的清单。",
  "home.who4.t": "怀疑的人",
  "home.who4.b": "你觉得这里面有不少是吹过头的。第 9 章是写给你的，而你多半有一部分是对的。",
  "home.metaDescription":
    "一份关于世界模型的免费交互式入门读物。这个词至少涵盖五种不同的机器，本站先把它们分开，再讲每一种怎么工作。",
  "home.contents": "目录",
  "home.mapTitle": "人们说的五种意思",
  "home.mapNote": "如果你不确定自己读到的是哪一种，从这里开始。",
  "home.premise": "前提",
  "home.audience": "写给谁看",
  "chapter.pdf": "PDF",
  "chapter.printNote": "本章的图都是可交互的。请到 {url} 在线按一按、拖一拖。",
  "chapter.prev": "← 上一章",
  "chapter.next": "下一章 →",
  "chapter.start": "起点",
  "chapter.atBeginning": "这里就是开头",
  "chapter.untranslated": "这一章还没有{lang}版本，下面的正文是英文原文。",
  "chapter.soon": "即将推出",
  "chapter.drafting": "撰写中",
  "chapter.readArrow": "阅读 →",

  "map.ordered": "按预测对象排序",
  "map.predicts": "预测{x}",
  "rb.aria": "两个模型从偏离演示轨迹 {n}% 的位置开始推演：一个越走越远，另一个回到轨迹上。",
  "rb.truthOnly": "只在演示轨迹上训练",
  "rb.recovery": "在邻近状态上练过恢复",
  "rb.demonstrated": "演示轨迹",
  "rb.first": "第一次预测",
  "rb.later": "十步之后",
  "rb.offset": "起始偏差",
  "rb.oneStep": "在演示轨迹上",
  "rb.oneStepA": "两者都预测得完全正确",
  "rb.truthEnd": "只看真值：第十步误差",
  "rb.recoveryEnd": "练过恢复：第十步误差",
  "id.nominal": "训练日志记下的转移数",
  "id.real": "真实转移",
  "id.dreamUseful": "有效的想象转移",
  "id.effective": "有效经验",
  "id.v.good": "这里的模型足够准确，合成批次里的大部分仍然带着有效信号。",
  "id.v.thin": "日志写着 100 次转移。把模型误差的累积算进去，学习者实际拿到的少得多。",
  "id.v.bad": "合成批次又大又不可靠：计数器涨了，学习者却在挨饿。",
  "id.share": "想象数据占比",
  "id.error": "每步模型误差",
  "id.reliability": "合成数据可靠度",
  "id.contactCost": "接触世界的代价",
  "id.computeCost": "模型计算代价",
  "fs.mean": "预测平均值",
  "fs.samples": "采样多个未来",
  "fs.left": "向左的未来",
  "fs.average": "平方误差最优解",
  "fs.right": "向右的未来",
  "fs.leftChance": "向左的概率",
  "fs.draw": "重新采样",
  "fs.sharp": "单次预测",
  "fs.sharp.no": "是糊的：落在两个结果之间。",
  "fs.sharp.yes": "是清晰的：每次采样都是一个可能结果。",
  "fs.uncertainty": "不确定性",
  "fs.uncertainty.kept": "保留为多个未来的分布。",
  "fs.uncertainty.lost": "被压成一张平均画面。",
  "af.aria": "模型的动作保真度为 {n}% 时，三条指令对应的轨迹。",
  "af.command.0": "指令：向左",
  "af.command.1": "指令：直行",
  "af.command.2": "指令：向右",
  "af.sameStart": "同一起始帧",
  "af.realized": "实际生成的运动",
  "af.fidelity": "动作保真度",
  "af.input": "动作输入",
  "af.input.yes": "每一行都有",
  "af.separation": "左右轨迹间距",
  "af.verdict": "控制检验",
  "af.v.ignored": "模型基本忽略了指令。",
  "af.v.weak": "指令改变了视频，但影响很弱。",
  "af.v.strong": "不同指令产生了清楚不同的轨迹。",
  "fm.risk.persistence": "持久性",
  "fm.risk.action": "动作保真度",
  "fm.risk.horizon": "长预测步长",
  "fm.risk.target": "目标质量",
  "fm.risk.verification": "可验证性",
  "fm.contract.renderer": "渲染器",
  "fm.contract.simulator": "仿真器",
  "fm.contract.dynamics": "动力学模型",
  "fm.contract.representation": "表征模型",
  "fm.contract.implicit": "内隐模型",
  "fm.level.0": "不是核心问题",
  "fm.level.1": "低风险",
  "fm.level.2": "实质风险",
  "fm.level.3": "决定性风险",
  "fm.askFirst": "面对{system}，先问这个",
  "fm.question.persistence": "同一个物体离开视野再回来之后，还是它自己吗？",
  "fm.question.action": "不同指令是否稳定地产生各自对应的不同未来？",
  "fm.question.horizon": "它吃着自己的输出能跑多远，答案才不再足以支撑决策？",
  "fm.question.target": "训练目标允许丢掉或塌缩哪些信息？",
  "fm.question.verification": "什么观测能证明它声称拥有的内部模型其实并不存在？",
  "fm.contract": "系统契约",
  "fm.binding": "决定性问题",
  "wb.steps": "推演到第几步",
  "wb.holdsTo": "大约撑到 {n}",
  "wb.colour": "颜色和光照保持不变",
  "wb.texture": "表面看起来还是它自己",
  "wb.layout": "房间还是同一个形状",
  "wb.count": "东西的数量还是那么多",
  "wb.physics": "东西的下落和碰撞还合乎道理",
  "wb.identity": "那还是刚才那个物体",
  "wb.gone": "没了",
  "wb.holding": "还在",
  "wb.brokenCount": "已经丢掉的性质",
  "wb.stillLooks": "然而",
  "wb.v.fine": "还什么都没丢。下游的一切仍然可以信任。",
  "wb.v.looksOk": "它看起来还很像样。坏掉的那些，不是你会去看的那些。",
  "wb.v.gone": "它看起来仍然像个场景，只是不再是关于任何具体东西的场景了。",
  "nr.fidelity": "看起来对",
  "nr.consistency": "保持一致",
  "nr.control": "让它做什么就做什么",
  "nr.cost": "跑起来便宜",
  "nr.sys.a": "系统 A",
  "nr.sys.b": "系统 B",
  "nr.sys.c": "系统 C",
  "nr.fidelity.note": "画面质量，也就是演示的用料，以及逐像素打分所奖励的东西。",
  "nr.consistency.note": "在长推演里世界还撑不撑得住，这是智能体需要的，也是演示因为太短而展示不了的。",
  "nr.control.note": "你给它的动作是不是它执行的动作，这就是世界模型和视频之间的差别。",
  "nr.cost.note": "跑一次推演要多少代价，这决定了有没有东西负担得起在里面做搜索。",
  "nr.bestBy": "按这个尺度最好的",
  "nr.overall": "综合最好的",
  "nr.overallA": "目前没有公认的办法把这几项合起来，所以这个问题现在没有答案。",
  "ep.speed": "发射速度",
  "ep.band": "它训练时见过的速度范围",
  "ep.axis": "扔得有多用力",
  "ep.faster": "更用力",
  "ep.true": "它真正落在哪里",
  "ep.says": "模型说落在哪里",
  "ep.off": "偏差",
  "ep.inside": "在它见过的范围里。任何在这里做测试的人都会说它掌握了这条规律。",
  "ep.outside": "在范围之外。它并没有那条规律，它只有一条穿过它见过那一段的直线。",
  "ep.aria": "真实的抛射距离与模型的预测随发射速度的变化；当前为 {v} 米每秒，模型偏差 {e}%。",
  "ac.left": "按住左",
  "ac.straight": "什么都不按",
  "ac.right": "按住右",
  "ac.none": "没有动作",
  "ac.given": "前两帧是给定的",
  "ac.made": "其余都是编出来的",
  "ac.action": "动作",
  "ac.condOn": "动作已输入",
  "ac.condOff": "没有输入动作",
  "ac.note.on": "一个模型，一个起点，三个未来。你拿到哪一个，由你决定。",
  "ac.note.off": "三行完全一样。没有动作，就只有一个未来可选：模型认为最可能的那一个。",
  "pb.chance": "往上走的概率",
  "pb.up": "一种可能的未来（{p}%）",
  "pb.down": "另一种（{p}%）",
  "pb.best": "可能最好的像素预测",
  "pb.q": "中间那格是一件会发生的事吗？",
  "pb.a.blur": "不是。它是两个未来同时存在，而这两个都不是它。",
  "pb.a.sure": "接近了。当某一个结果几乎确定时，平均值也就几乎就是那个结果。",
  "pb.scoreQ": "它的得分比两个真实未来都好吗？",
  "pb.scoreA": "是的。在一组结果上的平方误差由它们的平均值最小化，所以最优解是一张什么都不是的画面。",
  "cl.loss": "预测有多接近",
  "cl.spread": "表征还说得出多少东西",
  "cl.axis": "训练步数",
  "cl.step": "第几步",
  "cl.guardOff": "没有防护",
  "cl.guardOn": "防护已开",
  "cl.verdict": "你手里拿到的是",
  "cl.v.dead": "满分，外加一个空的表征。所有东西都编码到同一个点上。",
  "cl.v.going": "正在往下掉。「猜对」最省事的办法，就是什么都不说。",
  "cl.v.alive": "一个更差、而且永远到不了零的损失，以及一个仍然能区分东西的表征。",
  "cl.aria": "训练过程中的损失与表征离散度，防抗塌缩防护处于{g}状态。",
  "db.real": "在世界里走的步数",
  "db.imagined": "在模型里走的步数",
  "db.ratio": "每一步真实对应多少步想象",
  "db.contact": "花在世界里的时间",
  "db.wall": "总时间，含想象",
  "db.versus": "如果全都是真实的",
  "db.note": "这个学习者需要 {total} 步经验，来自哪儿都行。拖动这个比例并不会改变这一点，它改变的是这些步从哪儿来，以及由哪份预算来付。",
  "db.v.none": "没有模型。每一步经验都按全价从世界里买。",
  "db.v.some": "大部分经验现在是想象出来的，接触时间也跟着掉下来了。",
  "db.v.lots": "几乎全靠想象了。模型供不供得上，是下一幅图的问题。",
  "dt.temp": "梦里的不确定性",
  "dt.inDream": "在梦里的分数",
  "dt.inWorld": "在世界里的分数",
  "dt.gap": "梦减去世界",
  "dt.axisLow": "一个笃定的梦",
  "dt.axisHigh": "一个噪声大到学不动的梦",
  "dt.v.exploit": "在里面出色，在外面没用。策略找到了模型的怪癖，并在上面搭房子。",
  "dt.v.good": "里面难到只有真正管用的东西才活得下来。",
  "dt.v.noise": "现在里面已经没有任务可学了。两条分数一起塌。",
  "dt.aria": "在梦里的分数与在世界里的分数，按梦被赋予多少不确定性画出，当前设置为 {t}。",
  "fr.steps": "往前推的步数",
  "fr.bias": "模型每一步错多少",
  "fr.real": "实际发生的",
  "fr.forced": "每一步都被纠正，就像训练时那样",
  "fr.free": "放它自己吃自己的答案",
  "fr.offForced": "被纠正时，差了",
  "fr.offFree": "自己跑时，差了",
  "fr.ratio": "差了多少倍",
  "fr.aria": "同一个有缺陷的模型往前推 {n} 步、每步偏差 {b}%，一条是每步都被纠正的结果，另一条是让它吃自己输出的结果。",
  "mt.recurrent": "带一份摘要",
  "mt.attention": "留住上下文窗口",
  "mt.length": "到目前为止的步数",
  "mt.carried": "往前带的数字个数",
  "mt.carried.note": "下一步到来时，模型手里握着的东西。",
  "mt.perStep": "多走一步的计算量",
  "mt.perStep.note": "把一个新观测折进去所需的乘加次数。",
  "mt.reach": "它还看得到第一步吗？",
  "mt.reach.rec": "只有摘要留下了才行",
  "mt.reach.att": "还在上下文里时，可以看到",
  "mt.reach.note": "固定大小的摘要丢掉的东西，后面补不回来。",
  "mt.width": "两列用的状态都是 {d} 个数字宽，所以唯一在变的只有长度。",
  "mt.short": "还够短，全都看一遍反而是更便宜的那个选项。",
  "mt.mid": "过了交叉点。现在「留住上下文窗口」每一步的开销已经超过「更新一份摘要」了。",
  "mt.long": "到这里固定摘要才算物有所值，而它也开始丢东西了。",
  "lr.decoded": "这两个数解码出来的房间",
  "lr.pad": "这个空间本身。在里面任意拖动",
  "lr.z1": "墙有多远",
  "lr.z2": "能过去的口子在哪儿",
  "lr.picture": "画面里的数字个数",
  "lr.description": "描述里的数字个数",
  "lr.aria": "由两个数字（深度 {d}、偏移 {o}）画出来的房间，旁边是这两个数字所取自的那个二维空间。",
  "li.a": "一个房间",
  "li.b": "另一个房间",
  "li.pixel": "把两张画面平均一下",
  "li.latent": "把两个数字平均一下，再解码",
  "li.blend": "在两者之间走了多远",
  "li.pixelQ": "混出来的画面是个房间吗？",
  "li.pixelNo": "不是。它是两个房间同时叠在一起，而那不是你能走进去的东西。",
  "li.pixelYes": "在两端是。中间任何位置都不是。",
  "li.latentQ": "解码出来的那个是房间吗？",
  "li.latentYes": "是，滑块上每一处都是。那个空间里的每一个点都解码成一个房间。",
  "bn.width": "允许通过的数字个数",
  "bn.depth": "墙有多远",
  "bn.gap": "能过去的口子在哪儿",
  "bn.tilt": "相机歪向哪边",
  "bn.clutter": "地上的碎石",
  "bn.grain": "传感器噪点",
  "bn.light": "有多亮",
  "bn.canYouAct": "你能决定接下来做什么吗？",
  "bn.act.0": "不能。什么都没通过。",
  "bn.act.1": "还差一点。你知道有多远，但不知道口子在哪儿。",
  "bn.act.2": "能。两个数字就是这整个决定。",
  "bn.spent": "多出来的宽度买到了什么",
  "bn.spent.lean": "还没有浪费。通过这道口子的每一样，都会改变你的做法。",
  "bn.spent.leaves": "碎石、噪点和光照。都是真实的细节，也都不会改变你的做法。",
  "bn.aria": "一个房间，由描述它的六个数字中的前 {k} 个重建出来。",
  "fts.seen": "已看到的帧数",
  "fts.frame": "第 {n} 帧",
  "fts.axis": "同一个球，被拍了几次",
  "fts.known": "你能推出来的",
  "fts.open": "仍然不确定的",
  "fts.known.1": "它在哪里。单独一张画面能告诉你的就只有这些。",
  "fts.known.2": "它在哪里、往哪个方向走、走得多快。",
  "fts.known.3": "以上全部，再加上它在加速还是在减速。",
  "fts.open.1": "任何方向，任何速度。这张画面什么都排除不了。",
  "fts.open.2": "路径会不会弯，往哪边弯。",
  "fts.open.3": "已经少到可以下判断了。",
  "fts.aria": "同一个球的多张照片，与已看到的 {n} 帧仍然相容的所有未来被画成一把扇形，帧数越多扇形越窄。",
  "pc.strength": "预测器",
  "pc.bits": "比特",
  "pc.perChar": "每个字符的比特数",
  "pc.message": "这条消息要花",
  "pc.saved": "缩短了",
  "pc.none": "没有模型",
  "pc.letter": "字母频率",
  "pc.bigram": "一个字母的上下文",
  "pc.trigram": "两个字母的上下文",
  "pc.word": "词与语法",
  "pc.strong": "一个好的预测器",
  "pc.none.note": "每个符号概率相同，所以每个符号花费相同。",
  "pc.letter.note": "光是知道 e 常见而 q 不常见，就已经省下了一些。",
  "pc.bigram.note": "q 后面跟 u 几乎不花钱。省下来的都在上下文里。",
  "pc.trigram.note": "有了两个字母的上下文，后面会来什么已经被收窄了大半。",
  "pc.word.note": "一旦它知道有哪些词、词怎么搭，整个词尾都是可以预料的。",
  "pc.strong.note": "大致就是香农测出的人类猜英文的水平，也是好的语言模型所在的位置。",
  "gca.run": "运行",
  "gca.pause": "暂停",
  "gca.again": "再来一次",
  "gca.reset": "重置",
  "gca.step": "已走的步数",
  "gca.real": "实际来的",
  "gca.guess": "它猜的",
  "gca.wrongBy": "最近的误差",
  "gca.weights": "它学到的东西",
  "gca.verdict": "目前情况",
  "gca.v.bad": "在瞎猜。它几乎还什么都没见过。",
  "gca.v.mid": "形状抓到了，转弯处还是慢半拍。",
  "gca.v.good": "基本贴上去了。没有人告诉过它规则。",
  "gca.aria": "一个预测器在猜测序列的下一个值并不断自我修正，这里显示的是走了 {n} 步之后的样子。",
  "gallery.renderer": "一帧，然后是下一帧。产出的是给你看的东西；房间之所以还在，只是因为它一直画得前后一致。",
  "gallery.simulator": "别的程序能打开的几何结构。有用来渲染的表面，下面还有给物理引擎去碰撞的碰撞网格。",
  "gallery.dynamics": "一个短向量，以及在你正考虑的动作下的下一个向量。没有人给这些数字起名字，它只需要能往前推。",
  "gallery.implicit": "根本不是一种输出。探针在一个从没被给过棋盘的网络里找到了棋盘状态，这是关于「里面长出了什么」的论断，而不是一个你能运行的东西。",
  "gallery.representation": "缺失部分的摘要，被预测成嵌入空间里的一个点，然后就丢掉了。它从不重画像素。",
  "map.offAxis": "不在这条轴上",
  "map.notASystem": "它不是一个可运行的系统",
  "map.moreConcrete": "更具体",
  "map.whatGetsPredicted": "被预测的是什么",
  "map.moreAbstract": "更抽象",
  "map.howToTell": "如何分辨",
  "map.prev": "上一个",
  "map.next": "下一个",
  "map.counter": "第 {n} / {total} 个",
  "map.whoTalks": "谁这样用这个词",
  "map.coveredIn": "对应章节",
  "map.chapterN": "第 {n} 章",
  "map.idle":
    "这个词被用来指五种东西。其中四种是你可以运行的系统；第五种是关于系统内部有什么的断言。任选其一。",

  "spill.query": "“世界模型”",
  "spill.count": "5 个互不相容的答案",
  "spill.turnsOut": "其实属于",


  "loop.idle": "每一种定义都专精于这个回路上的某一段。把鼠标移到任意一个上面。",
  "loop.intervene": "干预 · 世界已经不同了",
  "loop.observe": "观测",
  "loop.infer": "推断",
  "loop.predict": "预测",
  "loop.choose": "选择",

  "eq.hoverHint": "把鼠标移到公式的任意部分，或下面的任意短语上。",
  "eq.next": "接下来会发生什么",
  "eq.now": "你现在在哪里",
  "eq.act": "你做了什么",
  "eq.next.note": "未来一步的状态。这是唯一你不知道的部分，也是唯一由模型产出的部分。",
  "eq.now.note": "当前状态。是给定的，不是预测出来的。",
  "eq.act.note": "你采取的动作。改变它，预测就跟着变，而这正是模型能用来做选择的原因。",
  "roll.one": "下一个状态",
  "roll.many": "从这里到 H 的每一个状态",
  "roll.nowP": "你所处的同一个状态",
  "roll.plan": "一整套计划",
  "roll.one.note": "一步。这就是上图里那个模型，没有变。",
  "roll.many.note": "不是一次预测，而是一整段预测，每一次都建立在上一次之上。要走到这一步，模型必须吃下自己的输出，而误差正是在这里累积的。",
  "roll.now.note": "这个不会变大。无论你问多远，你仍然只站在一个地方，只有关于它的一次观测。",
  "roll.plan.note": "不再是一个动作，而是一串动作，这才让它成为一个计划而不是一次猜测。在这些序列上做搜索，就是规划。",
  "roll.askFor": "把要问的东西从",
  "roll.insteadOf": "换成",
  "roll.stillGet": "而你手里仍然只有",
  "roll.and": "以及",
  "loop.world": "世界",
  "loop.observation": "观测",
  "loop.belief": "信念",
  "loop.imagination": "想象",
  "loop.action": "动作",
  "loop.world.sub": "隐藏状态 sₜ",
  "loop.belief.sub": "内部状态 bₜ",
  "loop.imagination.sub": "可能的未来",
  "arch.observation": "观测",
  "arch.encoder": "编码器",
  "arch.latent": "潜在状态",
  "arch.dynamics": "动力学",
  "arch.decoder": "解码器",
  "arch.prediction": "预测",
  "arch.controller": "控制器",
  "arch.action": "动作",
  "arch.stateEstimate": "状态估计",
  "arch.dynamicsGiven": "动力学（给定）",
  "arch.dynamicsLearned": "动力学（学出来的）",
  "arch.latentDynamics": "潜在动力学",
  "arch.imaginedRollout": "想象出来的推演",
  "arch.predEmbedding": "预测的嵌入向量",
  "arch.aWorld": "一个你能走进去的世界",

  "eq.reading": "在给定",
  "eq.given": "和",
  "eq.and": "的条件下，",
  "roll.hint": "只有两处发生了变化。把鼠标移到任意一边看看是哪两处。",

  "quiz.verdict.ch3.all": "连最后两道也答对了。预测之所以能长出结构，是因为结构正是「少犯错」最省事的办法；而在一段录像上误差低，仍然只是关于那段录像的论断。",
  "quiz.verdict.ch3.most": "够用来读论文了。大家最常错的是探针那道和目标选择那道，而这两道问的都是：预测到底在奖励什么。",
  "quiz.verdict.ch3.few": "值得再过一遍。两个问题能定下大部分情况：下一刻取决于什么，以及你把什么放在了这个猜测的右边。",
  "quiz.verdict.ch4.all": "连最后两道也答对了。重建只是「留住重要东西」的替身，而瓶颈决定了它后面的一切还能拿到什么。",
  "quiz.verdict.ch4.most": "够用来读论文了。大家最常错的是「替身」那道，以及为什么「越小越好」并不成立。",
  "quiz.verdict.ch4.few": "值得再过一遍。两个问题能定下大部分情况：这道口子留下了什么，以及两个有效点之间的那个点有没有意义。",
  "quiz.verdict.ch5.all": "连前三道也答对了。单步误差衡量的是一份模型永远不会被要求做的工作，而后面的一切都由此而来。",
  "quiz.verdict.ch5.most": "够用来读论文了。大家最常错的是交叉点那道和「状态分两部分」那道，而这两道问的都是：模型被迫放弃了什么。",
  "quiz.verdict.ch5.few": "值得再过一遍。一个问题能定下大部分情况：这一步交到它手里的，是真相，还是它自己上一次的答案？",
  "quiz.verdict.ch6.all": "连最后三道也答对了。想象改变的是汇率，而这一章里的每一道防护都只是让评分更难被钻空子，而不是让它变正确。",
  "quiz.verdict.ch6.most": "够用来读论文了。大家最常错的是「第二圈」那道，以及为什么训练出来的策略比一份方案更难被抓住。",
  "quiz.verdict.ch6.few": "值得再过一遍。一个问题能定下大部分情况：训练的时候，是谁在批改？",
  "quiz.verdict.ch7.all": "连最后两道也答对了。嵌入损失已经不再是一个你能直接读出好坏的数字，而这个论点也比它通常被喊出来的那句口号窄得多。",
  "quiz.verdict.ch7.most": "够用来读论文了。大家最常错的是「放弃了固定目标」那道，以及这并不是一个反对生成本身的论证。",
  "quiz.verdict.ch7.few": "值得再过一遍。一个问题能定下大部分情况：当未来真的还没定时，这个损失在要求模型画出什么？",
  "quiz.verdict.ch8.all": "连中间那三道也答对了。在训练过的范围里对得上，正是一个拟合函数会做的事，而输出很有说服力并不构成证据。",
  "quiz.verdict.ch8.most": "够用来读论文了。大家最常错的是「一致性到底靠什么撑着」，以及为什么这类系统的形状不适合在里面做规划。",
  "quiz.verdict.ch8.few": "值得再过一遍。一个问题能定下大部分情况：这个演示是不是落在它训练过的范围里？",
  "quiz.verdict.ch9.all": "连最后一道也答对了。它输出什么，以及你能不能在没人执行过的动作下把它往前推。这个问题贯穿整门课。",
  "quiz.verdict.ch9.most": "够用来读论文了。大家最常错的是「为什么平均误差一直很低」，以及「为什么任务成功率定不了案」。",
  "quiz.verdict.ch9.few": "值得再过一遍。一个问题能定下大部分情况：这个说法用的是哪个尺度，而那个尺度忽略了什么？",
  "quiz.verdict.ch1.all": "连那道陷阱题也答对了。一个系统被拿来做什么，并不决定它属于哪一类；它输出什么才决定。",
  "quiz.verdict.ch1.most": "够用来读论文了。大家最常错的是那道陷阱题，以及「保持一致本身什么也证明不了」这一点。",
  "quiz.verdict.ch1.few": "值得再过一遍。两个问题能定下大部分情况：它实际输出什么，以及你一开始被给到的是什么。",
  "quiz.verdict.ch2.all": "连关于信任的那两道也答对了。模型靠预测后果挣得自己的位置，又在搜索被允许跑到证据前面的那一刻失去它。",
  "quiz.verdict.ch2.most": "够用来读论文了。大家最常错的是集成那道和反事实那道，而这两道问的都是：一个模型的权威能延伸到多远。",
  "quiz.verdict.ch2.few": "值得再过一遍。两个问题能定下大部分情况：你能不能在没人执行过的动作下把它往前推，以及它被允许在哪里出错。",
  "dyn.hint": "把鼠标移到公式的任意部分，或下面的任意短语上。",
  "dyn.hat": "学出来的，所以只是个估计",
  "dyn.next": "你会落到哪里",
  "dyn.worth": "这一步值多少",
  "dyn.now": "你现在在哪里",
  "dyn.act": "你可能采取的一个动作",
  "dyn.hat.note": "这个帽子就是整章的要点。它表示「估计的」。这是从经验里拟合出来的模型，不是世界本身，后面出的所有问题都出在这里。",
  "dyn.next.note": "往前一步的状态。由模型产出，不是观测到的。这是唯一没有人交给你的部分。",
  "dyn.worth.note": "回报。并不是每个学出来的模型都预测它，但规划器需要有个东西可以打分，所以大多数都会预测。",
  "dyn.now.note": "你所在的位置，压缩过的。它不必是位置和速度，只需要装下下一步预测所依赖的东西。",
  "dyn.act.note": "动作。改变它，预测就跟着变，而这正是这东西能用来做选择的全部理由。",
  "dyn.read.0": "在给定",
  "dyn.read.1": "和",
  "dyn.read.2": "的条件下，该期待",
  "dyn.read.3": "以及",
  "dyn.read.4": "是什么。",
  "am.modelScore": "模型给出的分数",
  "am.realScore": "实际发生的结果",
  "am.notEqual": "不等于",
  "am.unless": "除非模型在搜索会去的地方也足够准。",
  "am.bestModel": "模型说这里最好",
  "am.bestReal": "实际上这里最好",
  "am.axis": "你能采取的每一个动作",
  "am.pick": "选一个动作",
  "am.agree": "这里两条曲线是一致的，空间里大部分地方都这样。",
  "am.diverged": "这里就不一致了。这一段正是模型最缺数据的地方。",
  "am.modelSays": "模型说",
  "am.reallyGet": "实际得到",
  "am.aria": "同一组动作上的两条打分曲线。它们几乎处处一致，只在模型相信的那一个窄峰上分道扬镳。",
  "comp.horizon": "往前推几步",
  "comp.given": "世界给的",
  "comp.imagined": "模型在读自己的答案",
  "comp.errorAxis": "到这一步已经错了多少",
  "comp.perStep": "模型自己每一步的误差",
  "comp.gain": "每一步的放大倍数",
  "comp.gainStat": "每一步的放大倍数",
  "comp.linear": "放大倍数为 1.00 时什么都不会被放大，误差只是单纯累加。一条直线，没有意外。",
  "comp.after": "推 {h} 步之后的误差",
  "comp.fine": "还够准，可以据此行动。",
  "comp.drifting": "在漂了。没有哪一步坏掉，只是一直在累加。",
  "comp.gone": "已经差得没边了。同一个模型，同样的每步误差。",
  "comp.aria": "一串预测出来的状态，第一个是给定的，其余都是模型基于自己的输出产生的。模型每一步引入 2% 的自身误差，已有误差每一步被放大 {gain} 倍；推 {h} 步之后累积误差达到 {pct}%。",
  "serve.watch.short": "看球",
  "serve.decide.short": "判断",
  "serve.swing.short": "移动挥拍",
  "serve.readToss.short": "读抛球",
  "serve.swingEarly.short": "177 毫秒起移动挥拍",
  "serve.net": "球网",
  "serve.server": "发球方",
  "serve.returner": "接发球方",
  "serve.speed": "发球速度",
  "serve.contact": "球拍击中球",
  "serve.ball": "球",
  "serve.arrives": "球到达",
  "serve.react": "看清再说",
  "serve.early": "提前读出来",
  "serve.watch": "看球",
  "serve.decide": "判断球的落点",
  "serve.swing": "移动并挥拍",
  "serve.swingEarly": "从 177 毫秒开始移动并挥拍",
  "serve.short": "差一点",
  "serve.readToss": "读抛球",
  "serve.inTime": "来得及",
  "serve.late": "晚了 {n} 毫秒",
  "serve.play": "发球",
  "serve.flight": "从球拍到接发球者的时间",
  "serve.verdictLabel": "在这个速度下",
  "serve.bothWork": "还够慢，看球再反应仍然行得通。两个人都来得及。",
  "serve.onlyEarly": "快到来不及看了。只有已经提前决定好的人赶得上。",
  "serve.neither": "已经越过了连提前判断都从容不了的界线。这里的回球是挡，不是打。",
  "serve.aria": "接一个 {kmh} 公里每小时、飞行 {ms} 毫秒的发球的时间预算，把一个看球再反应的接发球者和一个在抛球阶段就已决定的接发球者并排比较。",
  "exp.effort": "搜索力度",
  "exp.phantom": "模型以为存在的缺口",
  "exp.realGap": "唯一真实的缺口",
  "exp.inModel": "在模型里",
  "exp.inReality": "在现实里",
  "exp.succeeded": "到达目标",
  "exp.failed": "撞上墙",
  "exp.honest": "搜索还不够，没找到那个漏洞。它老老实实绕远路，于是成功了。",
  "exp.stuck": "还在搜索。",
  "exp.exploited": "它找到了那个并不存在的缺口。在想象里完美，在现实里撞墙。",
  "exp.aria": "一条穿过模型以为存在的缺口的规划，与同一条规划在缺口其实是实心墙的世界里执行的结果并排显示。",
  "plan.tried": "尝试的序列数",
  "plan.considered": "已考虑",
  "plan.hitWall": "会撞墙的",
  "plan.bestMiss": "距目标的最短距离",
  "plan.found": "找到绕过去的办法了。",
  "plan.allHit": "目前每一条序列都会撞墙。",
  "plan.closest": "目前最接近的一条，还差一点。",
  "plan.aria": "一个规划器采样 {n} 条动作序列，把每一条都在模型里推演一遍，然后留下最好的那条。",
  "hz.horizon": "预测步长 H",
  "hz.gapEvery": "每一步的偏差",
  "hz.steps": "已预测步数",
  "hz.gapNow": "当前偏差",
  "hz.worst": "至今最大偏差",
  "hz.units": "{n} 个步宽",
  "hz.v0": "目前还看不出差别。",
  "hz.v1": "开始分道扬镳。",
  "hz.v2": "已经是明显不同的未来。",
  "hz.v3": "其中一个晚了一步弹起，从此再也没能回来。",

  "quiz.of": "{i} / {n}",
  "quiz.score": "得分 {n}",
  "quiz.which": "这属于哪一种定义？",
  "quiz.pick": "选择一项",
  "quiz.right": "答对了",
  "quiz.wrong": "还差一点",
  "quiz.correct": "✓ 正确答案",
  "quiz.yours": "✗ 你的选择",
  "quiz.yoursShort": "✗ 你选的",
  "quiz.next": "下一题",
  "quiz.seeScore": "查看得分",
  "quiz.scored": "你的得分",
  "quiz.again": "再来一次",
  "quiz.answer": "答案",

  "video.nothing": "没有可看的画面",
  "video.talk": "讲座",

  "foot.body":
    "一份关于世界模型的免费入门读物。免费阅读，欢迎转发，也欢迎直接拿去用在你自己的课程里。注明出处即可。",
  "byline.by": "作者",
  "star.title": "这里的一切都是开源的",
  "star.body": "本站的文字、图表和每一个可交互组件都放在同一个公开仓库里。读它、纠正它，或者把某个组件拿去用在你自己的写作里。如果它对你有用，点个 star 是帮别人找到它最省事的办法。",
  "star.compact": "这一章是免费且开源的。点个 star，能帮下一个人找到它。",
  "star.button": "在 GitHub 上点亮 star",
  "foot.about": "关于",
  "foot.source": "源码",
};
