/**
 * The notes, in Chinese. Titles and author lines stay in the original: they are
 * what you type into a search box, and translating them would make the source
 * harder to find rather than easier.
 */
export const zh: Record<string, string> = {
  "https://www.worldlabs.ai/blog/taxonomy-of-world-models": "第一方给出的渲染器／仿真器／规划器三分法，是从智能体循环推出来的。",
  "https://doi.org/10.1115/1.3662552": "隐藏状态这条线的祖先。需付费。",
  "https://people.idsia.ch/~juergen/world-models-planning-curiosity-fki-1990.html": "把控制器和世界模型当作两个分开的对象，也就是这一章开头讲的那个区分。",
  "https://arxiv.org/abs/1803.10122": "编码器、潜在动力学、紧凑控制器，还包括把策略完全放在模型生成的环境里训练、再搬回真实环境的实验。",
  "https://arxiv.org/abs/1811.04551": "从图像里学出随机潜在动力学，然后在决策时对它做搜索。图 2.4 的真实版本。",
  "https://arxiv.org/abs/1912.01603": "在想象出来的潜在轨迹上训练 actor 和 critic，于是动手的那一刻不必再跑昂贵的搜索。",
  "https://www.nature.com/articles/s41586-025-08744-2": "同一个算法、同一套超参数，跑了 150 多个任务。这是想象这一支目前最强的证据。",
  "https://arxiv.org/abs/1911.08265": "最清楚的一个证明：规划并不需要重建观测。模型只学搜索会消费的那些量。",
  "https://arxiv.org/abs/2310.16828": "没有解码器的潜在动力学，配上局部轨迹优化，扩展到覆盖 104 个控制任务的单个多任务智能体。",
  "https://arxiv.org/abs/1805.12114": "集成加轨迹采样：把不确定性做进规划里，而不是当作事后补丁的标准做法。",
  "https://mlanthology.org/icml/1990/sutton1990icml-integrated/": "把规划定义成在学出来的模型上做计算，以及那个把它和真实经验交织起来的循环。",
  "https://papers.nips.cc/paper_files/paper/1990/hash/9be40cee5b0eee1462c82c6964087ff9-Abstract.html": "通过交互学出一个世界模型，再把它串起来优化未来的动作，比这个标签流行起来早了二十八年。",
  "https://arxiv.org/abs/1906.08253": "从真实状态出发的短推演，直接回应累积误差和模型利用。标题就是这一章的问题。",
  "https://arxiv.org/abs/1907.02057": "基于模型的方法到底在哪里赢、在哪里输，以及「往前看多远」这个两难在哪里被命名和度量。",
  "https://arxiv.org/abs/1906.08312": "每一种不确定性方法底下的那句警告：不确定性估计本身可能就是错的，而校正它会改变规划的结果。",
  "https://arxiv.org/abs/2005.13239": "把悲观写进目标：按模型的不确定性给预测回报打折，于是面生的捷径必须为「面生」付出代价。",
  "https://openreview.net/forum?id=BZ5a1r-kVsf": "整个论点的出处，包括为什么对一个要去行动的系统来说，预测外观是错的活。",
  "https://arxiv.org/abs/2006.07733": "那份缓慢更新的目标副本，以及那个让大家相信「不把东西推开也能避免塌缩」的结果。",
  "https://arxiv.org/abs/2105.04906": "显式的做法：惩罚那些各个分量已经塌掉或互相重复的表征。图 7.6 里那道防护的正经版本。",
  "https://arxiv.org/abs/2304.12210": "一份诚实的综述，包括这个领域有多大一部分是「防止平凡解获胜」的机器。",
  "https://arxiv.org/abs/2111.06377": "值得记住的反例：把被遮住那部分的像素重建出来，结果照样非常好用。",
  "https://arxiv.org/abs/2404.08471": "嵌入预测这个目标最后到底学到了什么，是测出来的，不是断言出来的。",
  "https://arxiv.org/abs/2301.08243": "预测被遮住区域的表征，而不是像素。",
  "https://ai.meta.com/blog/v-jepa-2-world-model-benchmarks/": "先做无动作预训练，再做动作条件下的控制。",
  "https://arxiv.org/abs/2408.14837": "DOOM 被逐帧地从此前的帧和输入里生成出来，快到可以玩。最清楚地说明了这类东西是可玩的，而不只是可看的。",
  "https://arxiv.org/abs/2411.02385": "图 8.7 的实测版本。视频模型在训练分布之内符合物理规律，出了这个范围就不会外推。",
  "https://openai.com/index/video-generation-models-as-world-simulators/": "让「涌现出物理」这个说法进入主流的那份报告。值得读一读它究竟主张了什么、又没主张什么。",
  "https://arxiv.org/abs/2501.03575": "把生成视频当作机器人和车辆的训练数据来造，而这正是这类系统毫无争议地擅长的用途。",
  "https://arxiv.org/abs/2311.17982": "对这个测量问题一次认真的尝试，也很适合用来看清：要拆到多少个互相独立的维度之后，排序才会变得不再显然。",
  "https://arxiv.org/abs/2402.15391": "可以用动作操控的生成环境。",
  "https://deepmind.google/blog/genie-3-a-new-frontier-for-world-models/": "报告称能在多分钟的交互里回想起先前见过的细节。",
  "https://www.worldlabs.ai/blog/marble-world-model": "高斯泼溅加碰撞网格：一次显式的结构导出。",
  "https://www.nvidia.com/en-us/ai/cosmos/": "一个边界案例：预测式视频世界与显式仿真并置。",
  "https://arxiv.org/abs/2210.13382": "在 Othello-GPT 内部找到棋盘状态，并且能对它做因果干预。",
  "https://arxiv.org/abs/2309.00941": "把这个发现进一步锐化的后续工作。",
  "https://arxiv.org/abs/2310.02207":
    "探针从一个大语言模型里读出了地点和日期，关于这一层意思的争论就是围绕这篇论文形成的。",
  "https://arxiv.org/abs/2010.02193": "同一个循环，做到了它开始打败那些直接从环境里学的智能体的规模。",
  "https://arxiv.org/abs/1703.06907": "同一个想法从机器人学那边过来：让模拟器的变化比现实还大，于是没有任何东西能依赖它的某一个版本。",
  "https://arxiv.org/abs/1910.07113": "把随机化推到足以把策略从模拟搬到真实硬件上，以及对这件事代价的一份诚实交代。",
  "https://arxiv.org/abs/1506.03099": "把这个错配点了名，并正面处理：训练时就让模型吃自己的预测，而且随着它变好逐步加量。",
  "https://arxiv.org/abs/1511.06732": "给整段推演打分，而不是给单步打分，好让被优化的东西就是你真正要跑的那个东西。",
  "https://arxiv.org/abs/1706.03762": "另一个答案：别再做摘要了，把每一步都留着，代价是开销随长度增长。",
  "https://arxiv.org/abs/2111.00396": "「做摘要」这条路带着更好的机器回来了，也是状态空间模型重新进入讨论的原因。",
  "https://arxiv.org/abs/2312.00752": "一份会根据自己正在看的东西来决定留什么的摘要，而这正是固定版本做不到的那个让步。",
  "https://doi.org/10.1162/neco.1997.9.8.1735": "那份固定摘要，被做成能比梯度愿意的更久地抓住一些东西。需付费。",
  "https://arxiv.org/abs/1312.6114": "变分自编码器。它加进去的噪声，正是这个空间最后能被走通、而不是变成一堆互不相干的地址的原因。",
  "https://doi.org/10.1126/science.1127647": "在有现代机器撑腰之前的瓶颈论证。需付费。",
  "https://arxiv.org/abs/1711.00937": "当那份简短描述被强制变成少数几个离散符号、而不是连续数字时，会发生什么。",
  "https://openreview.net/forum?id=Sy2fzU9gl": "把瓶颈上的压力调大，坐标轴就开始对上一些你叫得出名字的东西。这篇也很好地展示了那样做的代价。",
  "https://arxiv.org/abs/1606.05579": "「一个好的表征，是它的各个方向都有含义」这个主张，写在这个领域还不拥挤的时候。",
  "https://arxiv.org/abs/1811.12359": "证明一个重要边界：没有归纳偏置，纯无监督的解耦在一般情况下不可识别。瓶颈会施加压力，却不会自动给坐标轴命名。",
  "https://arxiv.org/abs/1610.09038": "不直接安排模型吃多少自己的输出，而是让教师强制和自由运行时的隐藏轨迹彼此相像。恢复能力必须进入训练目标。",
  "https://arxiv.org/abs/1710.11252": "像素预测对模糊问题的真正反驳：学习未来的分布，并从中采样清晰、各自可能的结果。",
  "https://arxiv.org/abs/2608.13552": "面向可交互世界模型的新基准：171 个场景，分别测试几何、交互保真度，以及物体离开和重返视野时的演化。",
  "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf": "一个符号的代价在这里变成了「你给它的概率」。预测与压缩是同一件事，一切都从这儿开始。",
  "https://doi.org/10.1002/j.1538-7305.1951.tb01366.x": "香农让人坐下来，一个字母一个字母地猜英文。图 3.10 最下面那一行大致就是他测出来的。",
  "https://doi.org/10.1207/s15516709cog1402_1": "训练一个小网络去预测下一个词，然后往里看：名词、动词、有生命与无生命，没有一样是被要求过的。",
  "https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf": "把「预测下一个词」放大之后，长出了没有人训练过的能力。这是「目标选择才是那个设计决定」最有力的证据。",
  "http://prize.hutter1.net/": "一项压缩维基百科快照的现金悬赏，理由是：不建模文本的含义，你就压不动它。",
  "https://arxiv.org/abs/1206.5538": "这篇综述梳理了「一个好的学出来的表征是拿来干什么的」，写在预测彻底赢下这场争论之前。",
  "https://people.idsia.ch/~juergen/creativity.html": "把压缩进展本身当作一种驱动力：它不只是衡量模型的尺子，也是跑去看点什么的理由。",
};
